[package]
name = "vendo"
version = "0.3.1"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive", "env"] }
clap_complete = "4.6.11"
comfy-table = "8.0.1"
indexmap = { version = "2.14.2", features = ["serde"] }
indicatif = "0.18.6"
jiff = "0.2.37"
open = "5.4.4"
owo-colors = { version = "4.4.0", features = ["supports-colors"] }
reqwest = { version = "0.13.5", default-features = false, features = ["json", "rustls", "query"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
tokio = { version = "1.53.2", features = ["rt", "macros", "net", "io-util", "time"] }
uuid = { version = "1.27.0", features = ["v4"] }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
